version: "3.9"
services:
  misp:
    image: tomcat:8-jdk8
    depends_on:
      - "db"
    ports:
      - "8080:8080"
    volumes:
      - "./webapps:/usr/local/tomcat/webapps"
      - "./utils:/utils"
  db:
    image: postgres:10
    environment:
      POSTGRES_USER: misp2
      POSTGRES_PASSWORD: secret
      POSTGRES_DB: misp2db
    volumes:
      - "./db:/docker-entrypoint-initdb.d"
      - "./pgdata:/var/lib/postgresql/data"

  compile:
    build:
      context: ../packages/docker-compile
      args:
        uid: 1000
        gid: 1000
    volumes:
      - ../:/mnt
    command: sh -c 'chmod +x /mnt/gradlew && /mnt/gradlew deployDevAdminTool deployDevOrbeon deployDevMisp --info'